const mainUl = document.querySelector('.item-list');
const itemLi = (task) => {
  const itemli = document.createElement('li');
  const div = document.createElement('div');
  const checkbox = document.createElement('input');
  const textContent = document.createElement('input');
  const btn = document.createElement('button');
  itemli.className = 'item';
  div.className = 'line';
  checkbox.className = 'my-checkbox';
  textContent.className = 'imput-text';
  btn.className = 'delete-btn';
  checkbox.setAttribute('type', 'checkbox');
  checkbox.setAttribute('value', 1);
  textContent.setAttribute('type', 'text');
  textContent.setAttribute('placeholder', '');
  mainUl.appendChild(itemli);
  itemli.appendChild(div);
  div.appendChild(checkbox);
  itemli.appendChild(textContent);
  itemli.appendChild(btn);
  textContent.value = task;
};
export default itemLi;